name: Helium CI/CD

on:
  push:
    branches: [ master ]

jobs:
  compile:
    name: Helium CI/CD
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Install Dependencies
      shell: bash
      run: |
        sudo apt-get update -y && sudo apt-get install -y libgtk2.0-0 zip
        wget https://packages.erlang-solutions.com/erlang/debian/pool/esl-erlang_22.3.1-1~ubuntu~bionic_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/w/wxwidgets3.0/libwxgtk3.0-0v5_3.0.4+dfsg-3_amd64.deb
        sudo apt install -y libdbus-1-dev autoconf automake libtool flex libgmp-dev cmake libsodium-dev libssl-dev bison libsnappy-dev libclang-dev doxygen make cargo g++ libsctp1 libncurses5 libwxbase3.0-0v5 build-essential cmake libdbus-1-dev mosh vim parallel
        sudo dpkg -i libwxgtk3.0-0v5_3.0.4+dfsg-3_amd64.deb
        sudo apt update -y
        sudo dpkg -i esl-erlang_22.3.1-1~ubuntu~bionic_amd64.deb
        sudo apt-get install -y -f
        
    - name: Compile and Zip
      shell: bash
      run: |
        ./rebar3 as validator release
        zip -r build-${{github.run_id}}.zip _build
        
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Upload files to S3 with AWS CLI
      run: |
        aws s3 cp build-${{github.run_id}}.zip s3://${{ secrets.AWS_BUCKET }}


