name: Erlang CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Compile
      shell: bash
      run: |
        sudo apt-get update -y && sudo apt-get install -y libgtk2.0-0
        wget https://packages.erlang-solutions.com/erlang/debian/pool/esl-erlang_22.3.1-1~ubuntu~bionic_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/w/wxwidgets3.0/libwxgtk3.0-0v5_3.0.4+dfsg-3_amd64.deb
        sudo apt install -y libdbus-1-dev autoconf automake libtool flex libgmp-dev cmake libsodium-dev libssl-dev bison libsnappy-dev libclang-dev doxygen make cargo g++ libsctp1 libncurses5 libwxbase3.0-0v5 build-essential cmake libdbus-1-dev mosh vim parallel
        sudo dpkg -i libwxgtk3.0-0v5_3.0.4+dfsg-3_amd64.deb
        sudo apt update -y
        sudo dpkg -i esl-erlang_22.3.1-1~ubuntu~bionic_amd64.deb
        sudo apt-get install -y -f
        cd miner
        ./rebar3 as validator release



        



        


